### ISSUE TITLE
Build the project step 'make' is not working as expected.

### ISSUE THREAD

**Issue by andrewjcraig** [IMC-UAS-Krems/OS3ILV-WS23-24-Assignment#2]
In the README.md, the last step of setup requires uses of make / makefile as a smoke test.

_Run the test (automatically build the project and instrument files for coverage):_
_make -f public/makefile test_

I'm currently attempting to execute this in Terminal on a MacBook (macOS Ventura 13.5.2).
I get the following error:
public/makefile:97: *** missing separator.  Stop.

From googling, the common response is this is an issue related to whitespace where there should be a tab character.

**Comment by alessiogambi** [comment]
We fixed this. Thanks
