### ISSUE TITLE
Generating coverage report in makefile not including all files

### ISSUE THREAD

**Issue by andrewjcraig** [IMC-UAS-Krems/OS3ILV-WS23-24-Assignment#8]
When running the command : make -f public/makefile coverage

The coverage report and testing is only covering the first file in src directory. In my case is Calc.c.
However, it does not generate coverage for the rest of the .c files in the directory.

Worth noting: make -f public/makefile test

This is working correctly.

**Comment by andrewjcraig** [comment]
This issue may be that the makefile is not correctly dropping the .gcda / .gcno files into build.objs directory and rather dropping those files into the root directory. So coverage is not reading them when called.

**Comment by alessiogambi** [comment]
This should be fixed in b66a6a0 by replacing `SRC_FILES_WITHOUT_MAIN` with `SRC_FILES_OUT_WITHOUT_MAIN` such that for linking the test cases, we use the compiled files, not the source files.

@andrewjcraig, please confirm that the issue is fixed and close the issue in that case.

**Comment by andrewjcraig** [comment]
Issue appears to be resolved with the latest changes to makefile.
Note to others: the changes brought stricter enforcement to compiling, so you may receive errors that require code refactoring where they did not exist with previous makefile compiles.
